-- 51_bloomberg_serie.sql
-- ---------------------------------------------------------------
-- Manual Bloomberg series registry, ported as-is from the SPP
-- monitor. One row per (ticker, campo, intervalo): what to request
-- from Bloomberg and the operational state of each series.
--
-- Deliberately separate from series_registry: this registry is
-- curated by hand from the dashboard (ad-hoc tickers, mixed
-- frequencies) while series_registry is the pipeline spine. Data
-- lands in bloomberg_dato, not fact_prices.
--
-- serie_id is assigned by the identity; the migration from the
-- monitor's database remaps its ids through the logical key, so no
-- caller ever supplies an explicit serie_id.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bloomberg_serie (
    serie_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is requested. ticker is what was typed and is displayed;
    -- ticker_clave is the folded form used for identity, because for
    -- Bloomberg 'spx index' and 'SPX Index' are the same security.
    ticker           TEXT NOT NULL,
    ticker_clave     TEXT NOT NULL,
    campo            TEXT NOT NULL,
    intervalo        TEXT NOT NULL DEFAULT 'diario',

    -- Display and request window
    descripcion      TEXT,
    moneda           TEXT,
    fecha_inicio     DATE,
    activa           BOOLEAN NOT NULL DEFAULT TRUE,

    -- Last-run trail, to spot series that fell behind
    ultima_fecha     DATE,
    ultimo_intento   TIMESTAMPTZ,
    ultimo_resultado TEXT,
    ultimo_error     TEXT,
    puntos           BIGINT DEFAULT 0,
    creada_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ticker_clave, campo, intervalo)
);
