-- 54_serie_manual.sql
-- ---------------------------------------------------------------
-- Registry of MANUAL price series: benchmark components (or any
-- auxiliary series) that no vendor provides - the counterpart of
-- the Bloomberg registry for data that is keyed in or pasted.
--
-- Same shape as bloomberg_serie/bloomberg_dato on purpose: a
-- registry row per series, values in long format in 55_. The
-- benchmark composition references these with fuente='manual'.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS serie_manual (
    serie_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       TEXT NOT NULL,
    descripcion  TEXT,
    moneda       TEXT,
    creada_en    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (nombre)
);
